[package]
name = "pinniped"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
clap = { version = "4.5.21", features = ["derive"] }
colored = "2.1.0"
log = "0.4.22"
pretty_env_logger = "0.5.0"
regex = "1.11.1"
